### ISSUE TITLE
Add Allowed Blocks to ensure only intentional blocks are enabled 

### ISSUE THREAD

**Issue by joesnellpdx** [10up/wp-scaffold#30]
**Is your enhancement related to a problem? Please describe.**
- Ensure only intended blocks are enabled from a commonly used list of blocks
- Ensure this pattern if followed on projects going forward to prevent *new* core blocks from being enabled without passing engineering (styling, functionality) 

**Describe the solution you'd like**
Allowed blocks list enabled

**Comment by fabiankaegy** [comment]
On a call with @joesnellpdx we briefly talked about this task and came up with the following possible solution. 

The goal here is that we want to have a way to dissable all Core Blocks (all blocks of a given namespace) unless we specifically whitelist these blocks. The caveat here is that with future WordPress Updates the new blocks that get introduced from Core should also automatically be on the ignore list. But custom blocks coming from Plugins etc should be allowed.

That means that instead of sending a whitelist of allowed blocks to core we want to send a blacklist of dissallowed blocks to core. But in our code we still want to be able to define a list of core blocks (blocks of a certain namespace) that we want to allow.

## Solution
We can create a whitelist for core blocks, use a core function to get the list of all core blocks. Do a `array_diff` to only have the list of items that are not on the whitelist left. We then do another `array_diff` between the list of all registered blocks and our list of items that we want to remove. Therefore leaving is with the list of blocks we want to enable.


### Code Example
```php
add_filter( 'allowed_block_types', 'restrict_core_blocks' );
function restrict_core_blocks() {
    $allowed_core_blocks = [
        'core/heading',
        'core/paragraph',
    ];
    
    function is_core_block( block_name ) {
        return str_starts_with( $block_name, 'core' )
    }
    
    $registered_blocks = WP_Block_Type_Registry::get_instance()->get_all_registered();
    $registered_core_blocks = array_filter( $registered_blocks, 'is_core_block' );
    
    $dissallowed_core_blocks = array_diff( $allowed_core_blocks, $registered_core_blocks );
    return array_diff( $registered_blocks, $dissallowed_core_blocks );
}
```
