### ISSUE TITLE
Include webpack.config.js

### ISSUE THREAD

**Issue by smy315** [10up/wp-scaffold#9]
With build scripts now coming from 10up-scripts, should we include webpack.config.js on root directory for both the theme and plugin? Just about every project requires some sort of updates to build script and I think this would be helpful. Maybe include a file with the following code commented out?

```
const defaultConfig = require('@10up/scripts/config/webpack.config');
module.exports = {
	...defaultConfig,
	myObject: {
        stuffHere: true
    }
};
```

I def think this is a file that every project will need.

**Comment by tlovett1** [comment]
We could certainly do that. Anyone else have any thoughts?

**Comment by joesnellpdx** [comment]
I suggest this plus clear guidance / reference in the readme.

**Comment by ryanwelcher** [comment]
@smy315 The @10up/scripts package has a fair amount of configuration options already  ( albeit not documented yet ). This is a great approach to more complicated additions but maybe we can hit more of the common ones so they can be passed via the `package.json` file the same way we have entry points, paths to CSS, etc?

Personally, I think we should document this rather than providing an example file because build processes are already complicated, and the existence of a file that is related to this build process but not being used might confuse things further. 

It also sends the message that this is the expected way to customize the build process for everything and we're directing users to update the package.json file to make customizations - which would again send mixed messages around the expected approach.

**Comment by smy315** [comment]
@ryanwelcher, you and TL provided more info about this just now. And it's also documented on 10up-scripts repo (li-comment-14265). I think we can close this out here since conversation belongs on 10up-scripts repo.
